In [25]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
df.time

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["time"] = encoder.fit_transform(df["time"])

In [28]:
df.time.unique()

array([0, 1])

In [29]:
x = df.drop(labels=["time"], axis= 1)
y = df.time

In [30]:
x.head()

   total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [32]:
from sklearn.pipeline import Pipeline    # And end-to-end runnig pipeline from pre-processing to model training
from sklearn.impute import SimpleImputer # I is used to handel missing vakues
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [33]:
categorical_col = ["sex", "smoker","day"]
numerical_col = ["total_bill", "tip", "size"]

In [ ]:
## numerical pipeline

num_pipeline = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy= "mean")),
        ("scaler", StandardScaler())
    ]
)   

## categorical pipeline

cat_pipeline = Pipeline(
    steps= [
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("OneHotEncoder", OneHotEncoder())
    ]
)

In [35]:
preprocessor = ColumnTransformer(
    [
        ("num_pipeline", num_pipeline, numerical_col),
        ("cat_pipeline", cat_pipeline, categorical_col)
    ]
)

In [36]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [37]:
## Model Automation
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

models = {
    "Random-Forest" : RandomForestClassifier(),
    "Decisiontree" : DecisionTreeClassifier()
}

In [42]:
def model_evaluation(X_train, X_test, y_train, y_test, models):
    report = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        model_score = accuracy_score(y_test, y_pred)
        report[name] = model_score
    return report

In [43]:
model_evaluation(X_train, X_test, y_train, y_test, models)

{'Random-Forest': 0.9591836734693877, 'Decisiontree': 0.9387755102040817}