### Dataframe in pyython 
In Python, a DataFrame is a two-dimensional, spreadsheet-like data structure where data is organized in a tabular format using rows and columns

In [12]:
import pandas as pd
import numpy as np


raw_data = {
    'Transaction_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1001, 1008, 1009, 1010],
    'Bedrooms': [3, 4, 2, np.nan, 5, 3, 4, 3, 2, 3, np.nan],
    'Square_Feet': [1500, 2200, np.nan, 1200, 3200, 1800, 2400, 1500, 950, 1650, 1100],
    'Neighborhood': ['Suburb', 'City', 'Suburb', 'Rural', 'City', np.nan, 'Rural', 'Suburb', 'Rural', 'City', 'Suburb'],
    'Has_Pool': ['Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No'],
    'House_Price': [250000, 420000, 180000, 150000, 550000, 290000, 380000, 250000, 130000, 310000, 165000]
}

df = pd.DataFrame(raw_data)
print(df)

    Transaction_ID  Bedrooms  Square_Feet Neighborhood Has_Pool  House_Price
0             1001       3.0       1500.0       Suburb      Yes       250000
1             1002       4.0       2200.0         City       No       420000
2             1003       2.0          NaN       Suburb       No       180000
3             1004       NaN       1200.0        Rural       No       150000
4             1005       5.0       3200.0         City      Yes       550000
5             1006       3.0       1800.0          NaN       No       290000
6             1007       4.0       2400.0        Rural      Yes       380000
7             1001       3.0       1500.0       Suburb      Yes       250000
8             1008       2.0        950.0        Rural       No       130000
9             1009       3.0       1650.0         City       No       310000
10            1010       NaN       1100.0       Suburb       No       165000

In [13]:
df.dtypes

Transaction_ID      int64
Bedrooms          float64
Square_Feet       float64
Neighborhood       object
Has_Pool           object
House_Price         int64
dtype: object

In [14]:
df["bathroom"] = df["Bedrooms"]-1

In [15]:
df

,Transaction_ID,Bedrooms,Square_Feet,Neighborhood,Has_Pool,House_Price,bathroom
0,1001,3.0,1500.0,Suburb,Yes,250000,2.0
1,1002,4.0,2200.0,City,No,420000,3.0
2,1003,2.0,NaN,Suburb,No,180000,1.0
3,1004,NaN,1200.0,Rural,No,150000,NaN
4,1005,5.0,3200.0,City,Yes,550000,4.0
5,1006,3.0,1800.0,NaN,No,290000,2.0
6,1007,4.0,2400.0,Rural,Yes,380000,3.0
7,1001,3.0,1500.0,Suburb,Yes,250000,2.0
8,1008,2.0,950.0,Rural,No,130000,1.0
9,1009,3.0,1650.0,City,No,310000,2.0
10,1010,NaN,1100.0,Suburb,No,165000,NaN

In [16]:
df1 = df

In [17]:
df1

,Transaction_ID,Bedrooms,Square_Feet,Neighborhood,Has_Pool,House_Price,bathroom
0,1001,3.0,1500.0,Suburb,Yes,250000,2.0
1,1002,4.0,2200.0,City,No,420000,3.0
2,1003,2.0,NaN,Suburb,No,180000,1.0
3,1004,NaN,1200.0,Rural,No,150000,NaN
4,1005,5.0,3200.0,City,Yes,550000,4.0
5,1006,3.0,1800.0,NaN,No,290000,2.0
6,1007,4.0,2400.0,Rural,Yes,380000,3.0
7,1001,3.0,1500.0,Suburb,Yes,250000,2.0
8,1008,2.0,950.0,Rural,No,130000,1.0
9,1009,3.0,1650.0,City,No,310000,2.0
10,1010,NaN,1100.0,Suburb,No,165000,NaN

In [35]:
df2 = df1.drop('Neighborhood', axis=1)
df2

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001       3.0       1500.0      Yes       250000       2.0
1             1002       4.0       2200.0       No       420000       3.0
2             1003       2.0          NaN       No       180000       1.0
3             1004       NaN       1200.0       No       150000       NaN
4             1005       5.0       3200.0      Yes       550000       4.0
5             1006       3.0       1800.0       No       290000       2.0
6             1007       4.0       2400.0      Yes       380000       3.0
7             1001       3.0       1500.0      Yes       250000       2.0
8             1008       2.0        950.0       No       130000       1.0
9             1009       3.0       1650.0       No       310000       2.0
10            1010       NaN       1100.0       No       165000       NaN

In [36]:
df3 = df2.copy()
df3

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001       3.0       1500.0      Yes       250000       2.0
1             1002       4.0       2200.0       No       420000       3.0
2             1003       2.0          NaN       No       180000       1.0
3             1004       NaN       1200.0       No       150000       NaN
4             1005       5.0       3200.0      Yes       550000       4.0
5             1006       3.0       1800.0       No       290000       2.0
6             1007       4.0       2400.0      Yes       380000       3.0
7             1001       3.0       1500.0      Yes       250000       2.0
8             1008       2.0        950.0       No       130000       1.0
9             1009       3.0       1650.0       No       310000       2.0
10            1010       NaN       1100.0       No       165000       NaN

In [40]:
df3["Bedrooms"] = df2["Bedrooms"].fillna(df2['Bedrooms'].mean())

In [ ]:
df3

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001  3.000000       1500.0      Yes       250000       2.0
1             1002  4.000000       2200.0       No       420000       3.0
2             1003  2.000000          NaN       No       180000       1.0
3             1004  3.222222       1200.0       No       150000       NaN
4             1005  5.000000       3200.0      Yes       550000       4.0
5             1006  3.000000       1800.0       No       290000       2.0
6             1007  4.000000       2400.0      Yes       380000       3.0
7             1001  3.000000       1500.0      Yes       250000       2.0
8             1008  2.000000        950.0       No       130000       1.0
9             1009  3.000000       1650.0       No       310000       2.0
10            1010  3.222222       1100.0       No       165000       NaN

In [44]:
df3['Bedrooms'] = df3['Bedrooms'].round(0).astype('Int64')
df3

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001         3       1500.0      Yes       250000         2
1             1002         4       2200.0       No       420000         3
2             1003         2          NaN       No       180000         1
3             1004         3       1200.0       No       150000      <NA>
4             1005         5       3200.0      Yes       550000         4
5             1006         3       1800.0       No       290000         2
6             1007         4       2400.0      Yes       380000         3
7             1001         3       1500.0      Yes       250000         2
8             1008         2        950.0       No       130000         1
9             1009         3       1650.0       No       310000         2
10            1010         3       1100.0       No       165000      <NA>

In [47]:
df4 = df3
df4["Square_Feet"] = df3['Square_Feet'].fillna(df3["Square_Feet"].mean()).round(0).astype("Int64")
df4

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001         3         1500      Yes       250000         2
1             1002         4         2200       No       420000         3
2             1003         2         1750       No       180000         1
3             1004         3         1200       No       150000      <NA>
4             1005         5         3200      Yes       550000         4
5             1006         3         1800       No       290000         2
6             1007         4         2400      Yes       380000         3
7             1001         3         1500      Yes       250000         2
8             1008         2          950       No       130000         1
9             1009         3         1650       No       310000         2
10            1010         3         1100       No       165000      <NA>

In [53]:
df5 = df4.copy()
df5['bathroom'] = df5['bathroom'].fillna(df5['bathroom'].median())
df5

    Transaction_ID  Bedrooms  Square_Feet Has_Pool  House_Price  bathroom
0             1001         3         1500      Yes       250000         2
1             1002         4         2200       No       420000         3
2             1003         2         1750       No       180000         1
3             1004         3         1200       No       150000         2
4             1005         5         3200      Yes       550000         4
5             1006         3         1800       No       290000         2
6             1007         4         2400      Yes       380000         3
7             1001         3         1500      Yes       250000         2
8             1008         2          950       No       130000         1
9             1009         3         1650       No       310000         2
10            1010         3         1100       No       165000         2

In [ ]:
pool = df5.groupby("Has_Pool")
pool

In [ ]:
df5["Has_Pool"]

0     Yes
1      No
2      No
3      No
4     Yes
5      No
6     Yes
7     Yes
8      No
9      No
10     No
Name: Has_Pool, dtype: object

In [57]:
pool_map = {"Yes" : 1, "No": 0}
df5["Has_Pool"] = df5["Has_Pool"].map(pool_map)

In [58]:
df5

    Transaction_ID  Bedrooms  Square_Feet  Has_Pool  House_Price  bathroom
0             1001         3         1500         1       250000         2
1             1002         4         2200         0       420000         3
2             1003         2         1750         0       180000         1
3             1004         3         1200         0       150000         2
4             1005         5         3200         1       550000         4
5             1006         3         1800         0       290000         2
6             1007         4         2400         1       380000         3
7             1001         3         1500         1       250000         2
8             1008         2          950         0       130000         1
9             1009         3         1650         0       310000         2
10            1010         3         1100         0       165000         2

In [59]:
df5.describe()

,Transaction_ID,Bedrooms,Square_Feet,Has_Pool,House_Price,bathroom
count,11.000000,11.0,11.0,11.000000,11.000000,11.0
mean,1005.090909,3.181818,1750.0,0.363636,279545.454545,2.181818
std,3.176619,0.873863,650.384502,0.504525,129585.001938,0.873863
min,1001.000000,2.0,950.0,0.000000,130000.000000,1.0
25%,1002.500000,3.0,1350.0,0.000000,172500.000000,2.0
50%,1005.000000,3.0,1650.0,0.000000,250000.000000,2.0
75%,1007.500000,3.5,2000.0,1.000000,345000.000000,2.5
max,1010.000000,5.0,3200.0,1.000000,550000.000000,4.0