In [5]:
import pandas as pd

C:\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [6]:
df = pd.read_csv(r"E:\sculptsoft\28 July\Twitter Sentiments.csv")
df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

### Performing text preprocessing

In [7]:
df = df.drop(columns=["id","label"])
df.head()

                                               tweet
0   @user when a father is dysfunctional and is s...
1  @user @user thanks for #lyft credit i can't us...
2                                bihday your majesty
3  #model   i love u take with u all the time in ...
4             factsguide: society now    #motivation

In [8]:
df["clean_text"] = df["tweet"].str.lower()
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,@user when a father is dysfunctional and is s...
1,@user @user thanks for #lyft credit i can't us...,@user @user thanks for #lyft credit i can't us...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,#model i love u take with u all the time in ...
4,factsguide: society now #motivation,factsguide: society now #motivation

In [9]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [10]:
def remove_punctuations(text):
    punctuations = string.punctuation
    return text.translate(str.maketrans("","",punctuations))

In [11]:
df["clean_text"] = df["clean_text"].apply(lambda x : remove_punctuations(x))
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...
1,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,model i love u take with u all the time in u...
4,factsguide: society now #motivation,factsguide society now motivation

In [12]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
stop_words = stopwords.words("english")
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data] Downloading package stopwords to C:\Users\Pratham
[nltk_data]     Langaliya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
stop_words = stopwords.words("english")
def remove_stop_words(text):
    return " ".join([word for word in text.split() if word not in stop_words])

In [14]:
df["clean_text"] = df["clean_text"].apply(lambda x : remove_stop_words(x))
df.head(10)

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time urð± ðððð...
4,factsguide: society now #motivation,factsguide society motivation
5,[2/2] huge fan fare and big talking before the...,22 huge fan fare big talking leave chaos pay d...
6,@user camping tomorrow @user @user @user @use...,user camping tomorrow user user user user user...
7,the next school year is the year for exams.ð...,next school year year examsð¯ cant think ð...
8,we won!!! love the land!!! #allin #cavs #champ...,love land allin cavs champions cleveland cleve...
9,@user @user welcome here ! i'm it's so #gr...,user user welcome im gr8

### Count the most frequent word and remove them

In [15]:
from collections import Counter

word_count = Counter()

for text in df["clean_text"]:
    for word in text.split():
        word_count[word] +=1

word_count.most_common(10)

[('user', 17473),
 ('love', 2647),
 ('day', 2198),
 ('happy', 1663),
 ('amp', 1582),
 ('im', 1139),
 ('u', 1136),
 ('time', 1110),
 ('life', 1086),
 ('like', 1042)]

In [16]:
frequent_word = set(word for (word,wc) in word_count.most_common(10))

def remove_frequent_word(text):
    return " ".join([word for word in text.split() if word not in frequent_word])

In [17]:
df["clean_text"] = df["clean_text"].apply(lambda x : remove_frequent_word(x))
df.head(10)

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,father dysfunctional selfish drags kids dysfun...
1,@user @user thanks for #lyft credit i can't us...,thanks lyft credit cant use cause dont offer w...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model take urð± ðððð ð¦ð¦ð¦
4,factsguide: society now #motivation,factsguide society motivation
5,[2/2] huge fan fare and big talking before the...,22 huge fan fare big talking leave chaos pay d...
6,@user camping tomorrow @user @user @user @use...,camping tomorrow dannyâ¦
7,the next school year is the year for exams.ð...,next school year year examsð¯ cant think ð...
8,we won!!! love the land!!! #allin #cavs #champ...,land allin cavs champions cleveland clevelandc...
9,@user @user welcome here ! i'm it's so #gr...,welcome gr8

### Removal of special character

In [18]:
import re

def remove_character(text):
    text = re.sub("[^a-zA-Z0-9]", " ", text)
    return text

In [19]:
df["clean_text"] = df["clean_text"].apply(lambda x : remove_character(x))
df.head(10)

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,father dysfunctional selfish drags kids dysfun...
1,@user @user thanks for #lyft credit i can't us...,thanks lyft credit cant use cause dont offer w...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model take ur
4,factsguide: society now #motivation,factsguide society motivation
5,[2/2] huge fan fare and big talking before the...,22 huge fan fare big talking leave chaos pay d...
6,@user camping tomorrow @user @user @user @use...,camping tomorrow danny
7,the next school year is the year for exams.ð...,next school year year exams cant think ...
8,we won!!! love the land!!! #allin #cavs #champ...,land allin cavs champions cleveland clevelandc...
9,@user @user welcome here ! i'm it's so #gr...,welcome gr8

### performing stemming

In [20]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [21]:
df["stemming"] = df["clean_text"].apply(lambda x : stem_words(x))
df.head()

,tweet,clean_text,stemming
0,@user when a father is dysfunctional and is s...,father dysfunctional selfish drags kids dysfun...,father dysfunct selfish drag kid dysfunct run
1,@user @user thanks for #lyft credit i can't us...,thanks lyft credit cant use cause dont offer w...,thank lyft credit cant use caus dont offer whe...
2,bihday your majesty,bihday majesty,bihday majesti
3,#model i love u take with u all the time in ...,model take ur,model take ur
4,factsguide: society now #motivation,factsguide society motivation,factsguid societi motiv

### Removal of url in a text

In [22]:
text = "https://www.pratham_langaliya.com this is the url of my website. Please go through it and subscribe my channel"

In [23]:
def removal_url(text):
    return re.sub(r'https://\S+|www\.\S+',' ',text)

In [24]:
print(removal_url(text))

  this is the url of my website. Please go through it and subscribe my channel

In [25]:
!pip install gensim

Requirement already satisfied: gensim in c:\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\anaconda3\lib\site-packages (from gensim) (2.5.0)
Requirement already satisfied: scipy>=1.7.0 in c:\anaconda3\lib\site-packages (from gensim) (1.18.0)
Requirement already satisfied: smart_open>=1.8.1 in c:\anaconda3\lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in c:\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [52]:
import gensim   
model = gensim.models.Word2Vec(window=10, min_count=1, workers=4)

In [43]:
model.corpus_count

31962

In [51]:
tokenized_text = (
    df["clean_text"].apply(lambda x: str(x).lower().split()).tolist()
)

In [53]:
model.build_vocab(tokenized_text, progress_per=100)

In [44]:
model.epochs

5

In [54]:
model.train(tokenized_text, total_examples=model.corpus_count, epochs=model.epochs)

(1193447, 1204290)

In [57]:
model.wv.most_similar("kid")

[('heres', 0.998323917388916),
 ('emotional', 0.997796356678009),
 ('9', 0.9977841973304749),
 ('yes', 0.9974474310874939),
 ('mark', 0.9972739815711975),
 ('piece', 0.997046947479248),
 ('member', 0.997001051902771),
 ('child', 0.9969965815544128),
 ('given', 0.9969744086265564),
 ('pa', 0.9968808889389038)]

In [56]:
df["clean_text"].sample(5)

5290      music therapy tool healing altwaystoheal healthy
25801     saturday afternoon planning wanderlust costarica
30061    eating      coyoacan mexico mexico mexicocity ...
19527    still blaming harper guys need professional he...
22198                  someones delighted park noraintoday
Name: clean_text, dtype: str

In [69]:
model.wv.similarity(w1 = "good", w2 = "music")

np.float32(0.8995699)